[project]
name = "h22-django"
version = "0.1.0"
description = ""
authors = [
    {name = "Kokc80",email = "kokc@inbox.ru"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django (>=6.0.2,<7.0.0)",
    "black (>=26.3.1,<27.0.0)",
    "redis (>=7.4.0,<8.0.0)"
]

[tool.poetry]
packages = [{include = "h22"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
# Максимальная длина строки
line-length = 119
# Исключены из проверки
exclude = '''
(
  /(
    \.git
    |.venv
    | venv
  )/
)'''
