# Generated by Django 6.0.2 on 2026-02-26 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idd_cat", models.IntegerField(verbose_name="Категория_ID")),
                ("name_cat", models.CharField(max_length=50, verbose_name="Категория")),
                ("descr", models.CharField(max_length=100, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name_cat"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idd_prod", models.IntegerField(verbose_name="Продукт_ID")),
                ("name_prod", models.CharField(max_length=50, verbose_name="Продукт")),
                ("descr", models.CharField(max_length=100, verbose_name="Описание")),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "cost",
                    models.FloatField(default=0.0, verbose_name="Цена за покупку"),
                ),
                ("date_created_at", models.DateField(verbose_name="Дата создания")),
                ("date_updated_at", models.DateField(verbose_name="Дата изменения")),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Введите категорию продукта",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["name_prod"],
            },
        ),
    ]
