# Generated by Django 6.0.2 on 2026-02-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="descr",
            new_name="descr_cat",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="descr",
            new_name="descr_prod",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="cost",
            new_name="price",
        ),
    ]
