# Generated by Django 6.0.2 on 2026-02-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_rename_descr_category_descr_cat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="idd_cat",
        ),
        migrations.RemoveField(
            model_name="catalog",
            name="idd_prod",
        ),
    ]
